cask-fonts and versions are deprecated
Error: homebrew/cask-x was deprecated. This tap is now empty and all its contents were either deleted or migrated.